namespace pika.servicios.organizacion;

public class CodigosError
{
    public const string ORGANIZACION_ERROR_DESCONOCIDO = "ORGANIZACION-ERROR-DESCONOCIDO";
    public const string ORGANIZACION_DATOS_NO_VALIDOS = "ORGANIZACION-DATOS-NO-VALIDOS";
    public const string ORGANIZACION_SIN_INTERPRETE_CONSULTA = "ORGANIZACION-SIN_INTERPRETE_CONSULTA";
    public const string ORGANIZACION_NO_HAY_INTERPRETE_CONSULTA = "ORGANIZACION-NO-HAY-INTERPRETE-CONSULTA";


    public const string ORGANIZACION_DOMINIO_NO_ENCONTRADA = "ORGANIZACION-DOMINIO-NO-ENCONTRADA";
    public const string ORGANIZACION_DOMINIO_ID_PAYLOAD_NO_INGRESADO = "ORGANIZACION-DOMINIO-ID-PAYLOAD-NO-INGRESADO";
    public const string ORGANIZACION_DOMINIO_ID_NO_INGRESADO = "ORGANIZACION-DOMINIO-ID-NO-INGRESADO";

    /// <summary>
    /// Codigos Errores de UnidadOrganizacional Hijo de Dominio.
    /// </summary>
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_NO_ENCONTRADA = "UNIDADORGANIZACIONAL-PERIODO-NO-ENCONTRADA";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ID_PAYLOAD_NO_INGRESADO = "UNIDADORGANIZACIONAL-PERIODO-ID-PAYLOAD-NO-INGRESADO";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ID_NO_INGRESADO = "UNIDADORGANIZACIONAL-PERIODO-ID-NO-INGRESADO";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ERROR_ACTUALIZAR = "UNIDADORGANIZACIONAL-PERIODO-ERROR-ACTUALIZAR";
    public const string ORGANIZACION_UNIDADORGANIZACIONAL_ERROR_ELIMINAR = "UNIDADORGANIZACIONAL-PERIODO-ERROR-ELIMINAR";

}
