namespace pika.servicios.contenido;

public class CodigosError
{
    #region Código de Error de servicios
    //CODIGOS GENERALES ERROR
    public const string CONTENIDO_DATOS_NO_VALIDOS = "CONTENIDO-DATOS-NO-VALIDOS";
    public const string CONTENIDO_ERROR_DESCONOCIDO = "CONTENIDO-ERROR-DESCONOCIDO";

    //CODIGOS ERROR - VOLUMEN
    public const string CONTENIDO_VOLUMEN_NO_ENCONTRADO = "CONTENIDO-VOLUMEN-NO-ENCONTRADO";


    //CODIGOS ERROR -  VOLUMENREPOSITORIO [N2]
    public const string CONTENIDO_VOLUMENREPOSITORIO_VOLUMEN_NO_ENCONTRADO = "CONTENIDO-VOLUMENREPOSITORIO-VOLUMEN-NO-ENCONTRADO";
    public const string CONTENIDO_VOLUMENREPOSITORIO_NO_ENCONTRADO = "CONTENIDO-VOLUMENREPOSITORIO-NO-ENCONTRADO";
    public const string CONTENIDO_VOLUMENREPOSITORIO_ID_PAYLOAD_NO_INGRESADO = "CONTENIDO-VOLUMENREPOSITORIO-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTENIDO_VOLUMENREPOSITORIO_ID_NO_INGRESADO = "CONTENIDO-VOLUMENTREPOSITORIO-ID-NO-INGRESADO";
    public const string CONTENIDO_VOLUMENREPOSITORIO_ERROR_ELIMINAR = "CONTENIDO-VOLUMENREPOSITORIO-ERROR-ELIMINAR";
    public const string CONTENIDO_VOLUMENREPOSITORIO_VOLUMENES_NO_ENCONTRADOS = "CONTENIDO-VOLUMENREPOSITORIO-VOLUMENES-NO-ENCONTRADOS";


    //CODIGOS ERROR - Version (EntidadVersion) [N3]
    public const string CONTENIDO_VERSION_NO_ENCONTRADO = "CONTENIDO-VERSION-NO-ENCONTRADO";
    public const string CONTENIDO_VERSION_ID_PAYLOAD_NO_INGRESADO = "CONTENIDO-VERSION-ID-PAYLOAD-NO-INGRESADO";
    public const string CONTENIDO_VERSION_ID_NO_INGRESADO = "CONTENIDO-VERSION-ID-NO-INGRESADO";
    public const string CONTENIDO_VERSION_ERROR_CONTENIDO = "CONTENIDO-VERSION-ERROR-CONTENIDO";
    public const string CONTENIDO_VERSION_ERROR_CONTENIDO_NO_ENCONTRADO = "CONTENIDO-VERSION-ERROR-CONTENIDO_NO_ENCONTRADO";
    public const string CONTENIDO_VERSION_ERROR_REPOSITORIO_NO_ENCONTRADO = "CONTENIDO-VERSION-ERROR-REPOSITORIO-NO-ENCONTRADO";

    #endregion



}

